name: Bug Report
description: Something with trufnetwork/evm-contracts is not working as expected.
title: "Bug: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report an issue. This form is for reporting **bugs in trufnetwork/evm-contracts**.

        If you have a **question** or are unsure if you have found a bug, please ask on the [Discord server](https://discord.com/invite/HzRPZ59Kay).

        When submitting logs, please submit them as text and not as a screenshot.
  - type: input
    id: version
    attributes:
      label: Version / Commit
      description: Please include the release version or commit hash of trufnetwork/evm-contracts you are using. Write `unknown` if you are unsure.
      placeholder: e.g. v0.0.1 or 1234567890abcdef
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating System
      description: Please include the operating system you are using.
      placeholder: e.g. Windows 10, Ubuntu 20.04, macOS 11.2.3
    validations:
      required: true
  - type: textarea
    id: configuration
    attributes:
      label: Configuration
      description: Please include a detailed description of your contract configuration, including your hardhat.config.ts, environment variables, and any other configuration flags you are using.
      placeholder: e.g. I am using the following hardhat.config.ts...
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: Please describe what you expected to happen.
      placeholder: e.g. I expected trufnetwork/evm-contracts to do X when I did Y
    validations:
      required: true
  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: Please describe what actually happened.
      placeholder: e.g. trufnetwork/evm-contracts did Z instead of X when I did Y
    validations:
      required: true
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Please describe the steps to reproduce the issue.
      placeholder: e.g. 1. Run trufnetwork/evm-contracts with the following command `npm run deploy`...
    validations:
      required: true
  - type: textarea
    id: additional_information
    attributes:
      label: Additional Information
      description: Please include any additional information that may be helpful.
      placeholder: e.g. I am using the following extensions `math` and `uuid`
    validations:
      required: false
