name: Issue Config
description: Configuration for issue templates
contact_links:
  - name: Ask a question
    url: https://github.com/trufnetwork/evm-contracts/discussions
    about: Please ask and answer questions here
blank_issues_enabled: true
